### PR TITLE
Added Kirchhoff-Love shell user example

### PR DESCRIPTION
**Pull request by SteinStoter**
With benchmark results from "Popular benchmark problems for geometric nonlinear analysis of shells"

### CODE REVIEW

**Comment by gertjanvanzwieten** [comment]
This looks great, thanks! A few minor suggestions:
- instead of `dotarg` you could consider using the Namespace's `add_field`: `ns.add_field(['u', 'uprev', 'upprev'], basis)` (note that this drops the 'dofs' suffix for argument names)
- this also cleans up the scalar arguments: `ns.add_field(['inc', 'incprev', 'incpprev'])`
- some of your expressions are very "airy", there is no need for spaces between parentheses and their content
- since Λ_sol contains (scalar) arrays, the displacement list logged at the end repeatedly shows the word "array". The easiest way to fix this is to append `float(args['inc'])` instead
- maybe it's actually more useful to log these lists as a csv or txt file instead?

The main thing missing in my mind is a plot of the roof as a whole. It may not have much value scientifically, but it is insightful for those unfamiliar with the benchmark and it provides a nice thumbnail for the example. I'm hoping that [plot_trisurf](https://matplotlib.org/stable/gallery/mplot3d/trisurf3d_2.html) will do the trick but don't believe I ever tried myself. If it's too much effort I'm happy to make an attempt on my side.

**Comment by SteinStoter** [comment]
I've given you access to both repositories.

Points 1 and 2:
I'm getting the error `AttributeError: 'Namespace' object has no attribute 'add_field'`. Should I use a different `Namespace` object?
More conceptually, though: I find the omission of 'dofs' dangerous, tbh. For Nutils starters (and even for more advanced users, as I have noticed), the distinction between the field and the array of coefficients that is dotted with a basis to create that field is quite confusing, since all Nutils examples use the same variable name for both. When taking `form.derivative(u)` for example; is `u` the field or the array of dofs? [<- not an actual question] 
I'd be a proponent of not using the same name for two (conceptually related but) different things. Feel free to edit that, though, if you more strongly value consistency among examples.

Point 3: I've removed the whitespace wherever I could find it.

Point 4: Done

Point 5: Done

About the plotting: sounds great! I don't think that is necessary before it can be added as a user example, but feel free to add that piece of code.

**Comment by gertjanvanzwieten** [comment]
I'll merge this with the updated has after we merged #12, which I want to use to select an interesting point on the load path for thumbnails

**Comment by gertjanvanzwieten** [comment]
Merged manually a7a974f

**Pull request closed without merging**
