### PR TITLE
Added hierarchical refinement example

### PR DESCRIPTION
**Pull request by CVerhoosel**

### CODE REVIEW

**Comment by CVerhoosel** [comment]
I have added another example, an immersed analysis of a potential flow problem. Could you please review it?

**Comment by gertjanvanzwieten** [comment]
Sorry, I was an inch away from merging this last year and must have been called away in the last second, I even had the merge commit ready but it wasn't pushed out yet. I just did so now - which means the hierarchical example is now merged (it will be on the website in the course of tomorrow). I will close this PR and open two new PRs to discuss the two examples you added since.

**Comment by joostvanzwieten** [comment]
It's [online](https://examples.nutils.org/user-hierarchical-mesh-regularization/) already.

**Comment by CVerhoosel** [comment]
Super. Thanks. I did not know how to split the different examples over different PRs, so thanks for doing that as well.

**Comment by gertjanvanzwieten** [comment]
SInce I was now the one to open the new PRs I'm actually not sure that you have permission to reply to my comments. If that is the case let me know and I'll go search for the right switch to flip.

**Pull request closed without merging**
